/** Isolated extension chrome: independent of the host page's styles. */
export const toolsStyle = `
:host{all:initial;color-scheme:light}*{box-sizing:border-box}[hidden]{display:none!important}
.question-navigation{display:flex;gap:6px;margin:8px 0}.question-navigation select{min-width:0;flex:1;font:inherit;border:1px solid #dce0e6;border-radius:5px;padding:5px}.reference-answer{font-size:13px;color:#2456c5;max-height:180px;overflow:auto;white-space:pre-wrap}
.wrap{font:12px/1.5 -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:#20242c;display:flex;flex-direction:column;align-items:flex-end;gap:10px}
.icon{width:14px;height:14px;flex:none;vertical-align:middle}
.ball{width:40px;height:40px;border:1px solid #dce0e6;border-radius:50%;background:#fff;color:#252a34;box-shadow:0 2px 12px #17243a1a;position:relative;cursor:pointer;font:750 27px/1 system-ui;touch-action:none;padding:0}
.ball-logo{display:block;width:100%;height:100%;border-radius:50%;pointer-events:none}
.ball::before{content:'';position:absolute;inset:-4px;border:2px solid #dfe5ee;border-radius:50%;pointer-events:none}.busy::before{border-color:#3265e8 #e1e8fa #e1e8fa #3265e8;animation:orbit 1s linear infinite}.review::before,.error::before{border-color:#c5923e}
.dot{position:absolute;right:-1px;top:0;width:9px;height:9px;border:2px solid white;background:#43866b;border-radius:50%}.paused .dot{background:#a2a9b5}.review .dot,.error .dot{background:#c5923e}
.panel{display:flex;flex-direction:column;width:320px;max-width:calc(100vw - 32px);max-height:min(70vh,560px);overflow:hidden;background:#fff;border:1px solid #dce0e6;border-radius:9px;box-shadow:0 5px 26px #17243a20}
header{display:flex;align-items:center;gap:7px;min-height:41px;padding:8px 12px;border-bottom:1px solid #e7e9ed;flex:none}.widget-logo{display:block;width:20px;height:20px;border-radius:4px;object-fit:contain}header strong{font-size:13px;font-weight:650;letter-spacing:-.3px}.phase{margin-left:auto;font-size:10px;color:#747b88}.panel-body{padding:10px 12px;overflow:auto;min-height:0;overscroll-behavior:contain}
p{margin:7px 0;white-space:pre-wrap;overflow-wrap:anywhere}.muted{color:#747b88;font-size:10px}.mode{margin:0 0 8px;padding-bottom:8px;border-bottom:1px solid #eff1f4;font-variant-numeric:tabular-nums}.message{font-size:11px;color:#526278;line-height:1.6;margin:5px 0 10px}.stem{font-size:12px;line-height:1.7;max-height:120px;overflow:auto}.answer{font-size:17px;font-weight:650;color:#3265e8;margin:10px 0}.answer:empty,.stem:empty{display:none}.explanation{margin:8px 0;color:#747b88}.explanation summary{font-size:10px;cursor:pointer}.details{font-size:11px;line-height:1.65;max-height:170px;overflow:auto}
.row{display:flex;flex-wrap:wrap;gap:5px;margin:0;padding:9px 12px;border-top:1px solid #e7e9ed;background:#fafbfc;flex:none}button{font:inherit;cursor:pointer}.control{display:inline-flex;align-items:center;justify-content:center;gap:5px;border:1px solid #dce0e6;padding:5px 8px;border-radius:5px;background:#fff;color:#555e6e;font-size:11px;min-height:28px}.control:hover{background:#f0f3f8}.primary{background:#3265e8;border-color:#3265e8;color:white}.primary:hover{background:#2858d0}.close{border:0;background:none;color:#747b88;font-size:19px;line-height:1;padding:0 2px;margin-left:4px}.hint{margin:0;padding:0 12px 8px;background:#fafbfc;font-size:10px;color:#838b98;flex:none}
.skip-history{margin:10px 0;border:1px solid #e7e9ed;border-radius:6px;overflow:hidden}.skip-history>summary{padding:8px 9px;background:#f7f8fa;font-size:11px}.skip-history summary{cursor:pointer;white-space:pre-wrap;overflow-wrap:anywhere;font-weight:500}.skip-history>p{padding:0 9px;font-size:10px}.skip-list{max-height:210px;overflow:auto;overscroll-behavior:contain;padding:0 9px}.skip-item{padding:8px 0;border-top:1px solid #e7e9ed}.skip-item summary{font-size:11px;line-height:1.65}.skip-item p{font-size:11px;font-weight:400}
.activity-log{list-style:none;padding:0;margin:10px 0 0;max-height:220px;overflow:auto;border-top:1px solid #eff1f4}.activity-log li{font-size:11px;line-height:1.6;padding:6px 0;border-bottom:1px solid #f2f3f5;overflow-wrap:anywhere;white-space:pre-wrap}.log-time{font-size:10px;color:#9299a6;margin-right:7px;font-variant-numeric:tabular-nums}.activity-log li[data-phase="error"]{color:#b54735}
button:focus-visible,summary:focus-visible{outline:2px solid #3265e8;outline-offset:2px}@keyframes orbit{to{transform:rotate(360deg)}}@media(prefers-reduced-motion:reduce){.busy::before{animation:none;border-style:dashed}}
`;
